# Generated by Django 4.1.7 on 2024-02-20 15:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0068_alter_notification_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
